name: Convert CSV to JSON

on:
  pull_request:
    paths:
      - 'resource/csv/master.csv'
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install csvtojson
        run: npm install -g csvtojson

      - name: Convert CSV to JSON
        run: |
          chmod +x resource/scripts/csvtojson.sh
          ./resource/scripts/csvtojson.sh resource/csv/master.csv static/master.json

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add static/master.json
          git commit -m "Update master.json"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload converted JSON
        uses: actions/upload-artifact@v4
        with:
          name: converted-json
          path: master.json